reddit-clone/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session
  resources :subs do
    resources :posts, only: [:new, :create]
  end
  resources :posts, only: [:edit, :show, :update, :destroy]
end

reddit-clone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  validates :title, :author_id, presence: true
  validate :has_sub?

  belongs_to(
    :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: 'User'
  )

  has_many :post_subs, dependent: :destroy

  has_many :subs, through: :post_subs

  private

    def has_sub?
      if self.subs.empty?
        flash[:errors] = "Post must have at least one Sub"
      end
    end
end

reddit-clone/app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :integer          not null, primary key
#  post_id    :integer          not null
#  sub_id     :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostSub < ActiveRecord::Base
  validates :post, uniqueness: { scope: :sub_id }
  validates :post, :sub, presence: true

  belongs_to :post
  belongs_to :sub

end

reddit-clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :title, uniqueness: true
  validates :moderator_id, :title, presence: true

  belongs_to(
    :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: 'User'
  )

  has_many :post_subs, dependent: :destroy

  has_many :posts, through: :post_subs
end

reddit-clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  validates :username, :session_token, uniqueness: true, presence: true
  validates :password_digest, presence: true

  has_many(
    :posts,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: 'Post'
  )
  has_many(
    :subs,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: 'Sub'
  )

  after_initialize :enforce_session_token

  def self.generate_session_token
    loop do
      token = SecureRandom.urlsafe_base64
      return token unless User.exists?(session_token: token)
    end
  end

  def self.find_by_credentials(params)
    user = User.find_by_username(params[:username])
    user.is_password?(params[:password]) ? user : nil
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def enforce_session_token
    self.session_token ||= User.generate_session_token
  end

end

reddit-clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :log_in_user!, :current_user

  def log_in_user!(user)
    user.reset_session_token!
    @current_user = user
    session[:session_token] = user.session_token
  end

  def log_out_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end
end

reddit-clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :only_author_can_edit, only: [:edit, :update]

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    PostSub.create(post: @post, sub_id: params[:sub_id])

    if @post.save
      redirect_to @post
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.delete
    redirect_to :index
  end

  private

    def post_params
      params.require(:post).permit(:title, :content, :url, sub_ids: [])
    end

    def only_author_can_edit
      unless current_user.id == Post.find(params[:id]).author_id
        flash[:errors] = "Only the author can edit"
        redirect_to Post.find(params[:id])
      end
    end
end

reddit-clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new

  end

  def create
    @user = User.find_by_credentials(session_params)
    if @user
      log_in_user!(@user)
      redirect_to @user
    else
      flash.now[:errors] = "Invalid username/password combination"
      render :new
    end
  end

  def destroy
    log_out_user!
    redirect_to new_session_url
  end

  private

    def session_params
      params.require(:session).permit(:username, :password)
    end
end

reddit-clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :only_moderator_can_edit, only: [:edit, :update]

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to @sub
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    if @sub.update(sub_params)
      redirect_to @sub
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def destroy
    @sub = Sub.find(params[:id])
    @sub.delete
    redirect_to :index
  end

  private

    def sub_params
      params.require(:sub).permit(:title, :description)
    end

    def only_moderator_can_edit
      unless current_user.id == Sub.find(params[:id]).moderator_id
        flash[:errors] = "Only the moderator can edit"
        redirect_to Sub.find(params[:id])
      end
    end
end

reddit-clone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_or_initialize_user

  def show

  end

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      redirect_to @user
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def edit

  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def destroy
    @user.delete
    redirect_to new_user_url
  end

  private

    def user_params
      params.require(:user).permit(:username, :password)
    end

    def find_or_initialize_user
      @user = params[:id] ? User.find(params[:id]) : User.new
    end
end

reddit-clone/app/helpers/subs_helper.rb
module SubsHelper
end

reddit-clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user.nil? %>
    <%= button_to "Log In", new_session_url, method: "get" %>
  <% else %>
    <%= button_to "Log Out", session_url, method: "delete" %>
  <% end %>

  <%= flash[:errors] if flash[:errors]%>

  <%= yield %>

</body>
</html>

reddit-clone/app/views/subs/index.html.erb
<h1>All the Subs</h1>

<% @subs.each do |sub| %>
  <%= link_to sub.title, sub %> <br>
<% end %>

<%= button_to "Make a New Sub", new_sub_url, method: "get" %>

reddit-clone/app/views/subs/new.html.erb
<h1>Create a Sub</h1>

<form action="<%= subs_url %>" method="post">
  <label>Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label>Description
    <input type="textarea" name="sub[description]" value="<%= @sub.description %>">
  </label>

  <input type="submit" value="Create">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
</form>

reddit-clone/app/views/subs/show.html.erb
<h1> <%= @sub.title %> </h1>

<p> <%= @sub.moderator.username %> </p>
<p> <%= @sub.description %> </p>

<ul>
  <% @sub.posts.each do |post| %>
    <li> <%= link_to post.title, post %> </li>
  <% end %>
</ul>

reddit-clone/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
  <label>Username
    <input type="text" name="user[username]" value="<%= @user.username %>">
  </label>
  <label>Password
    <input type="password" name="user[password]">
  </label>

  <input type="submit" value="Sign Up">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
</form>

reddit-clone/app/views/users/show.html.erb
<h1> <%= @user.username %> </h1>

<%= button_to "Make a New Sub", new_sub_url, method: "get" %>